# Generated by Django 2.2.5 on 2019-10-02 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191002_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teaser',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
