# Generated by Django 2.2.5 on 2019-10-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_teaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='main_img',
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
