"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h0^oe#*#l6xid8)4@u%8bg!4py2jdv3%(iv9$=zs55%if89vjt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['maxogryzko.dev', 'www.maxogryzko.dev', ".vercel.app"]

#  preventing the need for a database so I can deploy to vercel
if not os.getenv("VERCEL"):
    ALLOWED_HOSTS += ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'projects',
    'photos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.dummy"  # preventing the need for a database so I can deploy to vercel
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Add Vercel-specific configuration
if os.getenv("VERCEL"):
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static/'),
    ]
    
# For Vercel deployment
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Add WhiteNoise middleware for static files
if os.getenv("VERCEL"):
    # Insert WhiteNoise middleware right after SecurityMiddleware
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


FILE_UPLOAD_PERMISSIONS=0o640
FILE_UPLOAD_MAX_MEMORY_SIZE = 200000000



STATIC_PROJECTS = [
    {
        "title": "Jump Exaggeration App",
        "main_img": {"url": "/media/IMG_5729.gif"},
        "image2": None,
        "image3": None,
        "image4": None,
        "slug": "jump-exaggeration-app",
        "teaser": "Load in a video of a jump and autonomously exaggerate the jump vertical as much as you'd like, a la <a href='https://www.youtube.com/watch?v=mQ5D2Dh3vrM' target='_blank'>NBA Jam</a>.",
        "description": "Here's a detailed explanation of the project: ",
        "date": "2019-10-02 01:30:27",
        "skills": "Computer Vision, Deep Learning, Python",
        "tools": "Python, OpenCV, PyTorch",
        "github": "https://github.com/roop-pal/NBA-Jammifier"
    },
    {
        "title": "Deep Learning Based Wind Speed Simulation",
        "main_img": {"url": "/media/kpf_gif.gif"},
        "image2": None,
        "image3": None,
        "image4": None,
        "slug": "wind-speed-simulation",
        "teaser": "This work was featured by <a href='https://ui.kpf.com/smarter-city' target='_blank'>KPFui</a> at the <a href='https://www.nvidia.com/en-us/on-demand/session/gtcsj20-s21493/' target='_blank'>NVIDIA GTC 2020</a> conference.",
        "description": "I finetuned the <a href='https://github.com/phillipi/pix2pix' target='_blank'>pix2pix</a> GAN on a custom dataset of building facades and created an API on AWS Sagemaker that is then used in a <a href='https://www.grasshopper3d.com/' target='_blank'>Grasshopper</a> plugin. The model returns back an image with a wind speed value at each pixel, coded from red (0 m/s) to green (120m/s).",
        "date": "2019-10-02 01:27:24",
        "skills": "Deep Learning, Computer Vision, AWS",
        "tools": "Python, Pytorch, OpenCV"
    },
    {
        "title": "Building Recognition App",
        "main_img": {"url": "/media/building1_iphone.png"},
        "image2": {"url": "/media/building2_iphone.png"},
        "image3": {"url": "/media/building3_iphone.png"},
        "slug": "building-recognition-app",
        "teaser": "An app that leverages GPS, accelerometer, and barometer data to localize a user's location and orientation within a <a href='http://maps.nyc.gov/download/3dmodel/DA_WISE_GML.zip' target='_blank'>3D point cloud</a> of NYC. Buildings are identified in user's live camera feed and relevant information is provided once the building is identified.",
        "github": "https://github.com/roop-pal/nyc-visual-building-annotator",
        "date": "2019-10-02",
        "skills": "Computer Vision, 3D Reconstruction",
        "tools": "OpenCV, Python"
    },
    {
        "title": "AI NBA Player",
        "main_img": {"url": "/media/nba_ai1crop.gif"},
        "image2": {"url": "/media/ai_gif2.gif"},
        "image3": None,
        "image4": None,
        "slug": "basketball-game",
        "teaser": "An attempt to make my favorite NBA players play against me.",
        "description": "Using tracking data from the <a href='https://github.com/sealneaward/nba-movement-data' target='_blank'>2015-16 NBA season</a>, I created an algorithm that finds when a player I specify is guarding a ball-handler. I then trained an <a href='https://colah.github.io/posts/2015-08-Understanding-LSTMs/' target='_blank'>LSTM</a> to imitate the player as a \"ghost\" defender.\r\n\r\nBelow you see two real possessions from the 2015-16 NBA season. The ball handler is the black dot, the real defenderis the gold dot, and the AI I trained is the red dot.",
        "date": "2019-10-02 01:43:23",
        "skills": "Deep Learning, Python",
        "tools": "PyTorch, Python, NumPy, Pandas",
        "github": "https://github.com/mogryzko/NBA-Defensive-AI"
    }
]